// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWjc0x_EnODgPs-MfUDeZPhGLy-1RUAg',
    appId: '1:269558842359:web:e9b2cff961c7e8c5e264f2',
    messagingSenderId: '269558842359',
    projectId: 'e-money-b2979',
    authDomain: 'e-money-b2979.firebaseapp.com',
    storageBucket: 'e-money-b2979.firebasestorage.app',
    measurementId: 'G-1C662GRF3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexFx1c73GeD9gmthAYeIKRu2NsxM1kvc',
    appId: '1:269558842359:android:36765c4bfb51f681e264f2',
    messagingSenderId: '269558842359',
    projectId: 'e-money-b2979',
    storageBucket: 'e-money-b2979.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCexFx1c73GeD9gmthAYeIKRu2NsxM1kvc',
    appId: '1:269558842359:ios:c7b04ef081f59b7ce264f2',
    messagingSenderId: '269558842359',
    projectId: 'e-money-b2979',
    storageBucket: 'e-money-b2979.firebasestorage.app',
    iosBundleId: 'com.frontend.emoney',
  );
}
